package domain

case class RetailLocation(
retailerLocationName: String,
lat: Double, lon: Double,
networkId: String,
retailerLocId: String,
agencyNr: String,
activationStartDate: String,
activationEndDate: String,
vacationStart1: String,
vacationEnd1: String,
vacationStart2: String,
VacationEnd2: String,
VacationStart3: String,
vacationEnd3: String,
vacationStart4: String,
vacationEnd4: String,
holiday1: String,
holiday2: String,
holiday3: String,
holiday4: String,
locationAddress: String,
locationCity: String,
locationRegion: String,
locationPostalCode: String,
locationPhone: String,
locationEmail: String,
locationDirection: String,
workingDays: String,
OpeningHrDay1: String,
OpeningHrDay2: String,
OpeningHrDay3: String,
OpeningHrDay4: String,
OpeningHrDay5: String,
OpeningHrDay6: String,
OpeningHrDay7: String,
OpeningHrsHoliday: String,
isActive: String,
lastUpdate: String,
uniqueKey: String,
locationAddress2: String) {

}
